-- AlterTable: add new columns to Patient with safe defaults
ALTER TABLE `Patient`
  ADD COLUMN `birth_date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN `gender` ENUM('FEM','MASC','NONE') NOT NULL DEFAULT 'NONE',
  ADD COLUMN `height` DOUBLE NOT NULL DEFAULT 0,
  ADD COLUMN `weight` DOUBLE NOT NULL DEFAULT 0,
  ADD COLUMN `profile_picture` MEDIUMBLOB NULL,
  MODIFY `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);
