services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"  
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=4000

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NUXT_INTERNAL_API_BASE=http://backend:4000
      - NUXT_PUBLIC_API_BASE=http://localhost:4000
    depends_on:
      - backend
